using Microsoft.Extensions.Logging.Abstractions;
using Spectre.Console.Rendering;
using System.ComponentModel;
using System.Runtime.InteropServices;

namespace AspireRunner.Tool.Commands;

public class RunCommand : AsyncCommand<RunCommand.Settings>
{
    public class Settings : CommandSettings
    {
        [CommandArgument(0, "[version]")]
        [Description("The version of the dashboard to run")]
        public string? Version { get; set; }

        [CommandOption("-b|--browser")]
        [Description("Launch the dashboard in the default browser")]
        public bool LaunchBrowser { get; set; }

        [DefaultValue(18888)]
        [CommandOption("-p|--port")]
        [Description("The port the dashboard will be available on")]
        public int DashboardPort { get; init; }

        [CommandOption("-a|--auth")]
        [Description("Use browser token authentication for the dashboard")]
        public bool UseAuth { get; init; }

        [CommandOption("-t|--token")]
        [Description("The token to use for dashboard authentication, if not passed, the token will be randomly generated by the dashboard")]
        public string? AuthToken { get; set; }

        [CommandOption("-s|--https")]
        [Description("Use HTTPS instead of HTTP, this applies to both the dashboard and the OTLP server, Enabled by default")]
        public bool? UseHttps { get; init; }

        [CommandOption("--dashboard-https")]
        [Description("Use HTTPS instead of HTTP for the dashboard, overrides the global HTTPS option")]
        public bool? DashboardHttps { get; init; }

        [DefaultValue(4317)]
        [CommandOption("--otlp-port")]
        [Description("The port the OTLP/gRPC server will listen on, can be disabled by passing 0")]
        public int OtlpPort { get; init; }

        [CommandOption("--otlp-http-port")]
        [Description("The port the OTLP/HTTP server will listen on, by default, only the gRPC server is started")]
        public int? OtlpHttpPort { get; set; }

        [CommandOption("--otlp-key")]
        [Description("The API key to use for the OTLP server")]
        public string? OtlpKey { get; set; }

        [CommandOption("--otlp-https")]
        [Description("Use HTTPS instead of HTTP for the OTLP/gRPC and OTLP/HTTP endpoints, overrides the global HTTPS option")]
        public bool? OtlpHttps { get; set; }

        [CommandOption("--cors-origins")]
        [Description("The allowed origins for CORS requests, separated by a comma. A wildcard (*) can be used to allow any domain")]
        public string? CorsAllowedOrigins { get; set; }

        [CommandOption("--cors-headers")]
        [Description("The allowed headers for CORS requests, separated by a comma")]
        public string? CorsAllowedHeaders { get; set; }

        [CommandOption("--hostname")]
        [Description("The hostname used for the dashboard and OTLP server, 'localhost' by default")]
        public string? Hostname { get; set; }

        [CommandOption("-m|--multiple")]
        [Description("Allow running multiple instances of the dashboard, if not passed, existing instances will be replaced")]
        public bool AllowMultipleInstances { get; set; }

        [CommandOption("--auto-update")]
        [Description("Automatically update the dashboard to the latest version, Enabled by default")]
        public bool? AutoUpdate { get; set; }
    }

    private bool _dashboardRunning;
    private int _currentWidth = AnsiConsole.Profile.Width;
    private int _currentHeight = AnsiConsole.Profile.Height;

    public override async Task<int> ExecuteAsync(CommandContext context, Settings settings)
    {
        AnsiConsole.Write(Widgets.Header());
        AnsiConsole.Write(Widgets.RunnerVersion);
        AnsiConsole.Console.EmptyLines(2);

        // Prepare dashboard options
        Dashboard? dashboard = null;
        var dashboardOptions = BuildOptions(settings);
        var otlpEndpoints = GetEnabledEndpoints(dashboardOptions);

        // Register runner signal handlers
        void StopHandler(PosixSignalContext _) => dashboard?.StopAsync().Wait();
        using var sigInt = PosixSignalRegistration.Create(PosixSignal.SIGINT, StopHandler);
        using var sigTerm = PosixSignalRegistration.Create(PosixSignal.SIGTERM, StopHandler);

        // Create and start the dashboard
        await AnsiConsole.Status()
            .Spinner(Spinner.Known.Dots)
            .SpinnerStyle(new Style(Widgets.DefaultColor))
            .StartAsync("Initializing runner", async ctx =>
            {
                var dashboardFactory = new DashboardFactory(new NullLogger<DashboardFactory>(), new NullLoggerFactory());

                ctx.Status("Looking for installed dashboards");
                dashboard = await dashboardFactory.CreateDashboardAsync(dashboardOptions);

                if (dashboard is null)
                {
                    AnsiConsole.Write(Widgets.Error($"No dashboards found. Run '[bold]{RunnerInfo.CommandName} install[/]' to install the latest version."));
                    return;
                }

                if (settings.Version is not null && !VersionRange.Parse(settings.Version, true).IsSatisfied(dashboard.Version))
                {
                    dashboard = null;
                    AnsiConsole.Write(Widgets.Error($"No version matching '{settings.Version}' is installed, run '{RunnerInfo.CommandName} install {settings.Version}' to install it"));
                    return;
                }

                AnsiConsole.MarkupLineInterpolated($"Found dashboard version [{Widgets.DefaultColorText}]{dashboard.Version}[/] at {dashboard.InstallationPath}");

                ctx.Status("Starting dashboard process...");
                await dashboard.StartAsync(CancellationToken.None);
            });

        if (dashboard?.IsRunning is not true)
        {
            return -1;
        }

        _dashboardRunning = true;
        AnsiConsole.MarkupLine("Dashboard started successfully [green]✓[/]");
        AnsiConsole.Clear();

        // Prepare the main layout
        var defaultStatus = Widgets.StatusSymbol(false);
        var table = new Table()
            .BorderStyle(new Style(Widgets.DefaultColor, decoration: Decoration.Dim))
            .AddColumn("Dashboard", c => c.Centered().Width(30))
            .AddColumn("OTLP/gRPC", c => c.Centered().Width(30))
            .AddColumn("OTLP/HTTP", c => c.Centered().Width(30))
            .AddRow(defaultStatus, defaultStatus, defaultStatus);

        var actions = new Columns(
            Widgets.KeyActionDescriptor("S", "Stop"),
            Widgets.KeyActionDescriptor("R", "Restart"),
            Widgets.KeyActionDescriptor("B", "Open browser"),
            Widgets.KeyActionDescriptor("H", "Help"),
            Widgets.KeyActionDescriptor("Esc", "Exit")
        ).Collapse().PadRight(3);

        var mainLayout = new Layout("main").SplitRows(
            new Layout("header", new Align(new Rows(Widgets.Header(), Widgets.RunnerVersion).Collapse(), HorizontalAlignment.Left, VerticalAlignment.Top)).Ratio(5),
            new Layout("table", new Align(table, HorizontalAlignment.Left, VerticalAlignment.Bottom)).Ratio(6),
            new Layout("prompt", new Align(actions, HorizontalAlignment.Left, VerticalAlignment.Bottom)).Ratio(1)
        );

        // Render the live layout (with spinners) while the dashboard is still initializing
        await RenderLiveInitializationAsync();

        // Re-render the static layout
        mainLayout.Render();
        var lastRenderTime = DateTimeOffset.UtcNow;

        while (true)
        {
            if (CheckDashboardStatusChanged()
                | CheckConsoleSizeChanged()
                | CheckRenderTimeout())
            {
                mainLayout.Render();
            }

            if (Console.KeyAvailable)
            {
                var pressedKey = Console.ReadKey(true);
                switch (pressedKey.Key)
                {
                    case ConsoleKey.R:
                    {
                        await StopDashboardAsync();

                        await dashboard.StartAsync();

                        // Avoid launching the browser when restarting the dashboard
                        dashboardOptions.Runner.LaunchBrowser = false;
                        _dashboardRunning = dashboard.IsRunning;

                        await RenderLiveInitializationAsync();
                        mainLayout.Render();
                        break;
                    }
                    case ConsoleKey.H or ConsoleKey.Help:
                    {
                        if (PlatformHelper.GetUrlOpener(RunnerInfo.ProjectUrl) is { } opener)
                        {
                            ProcessHelper.Run(opener.Executable, opener.Arguments);
                        }

                        break;
                    }
                    case ConsoleKey.B:
                    {
                        if (dashboard.IsRunning && dashboard.Url is not null && PlatformHelper.GetUrlOpener(dashboard.Url) is { } opener)
                        {
                            ProcessHelper.Run(opener.Executable, opener.Arguments);
                        }

                        break;
                    }
                    case ConsoleKey.Escape:
                    {
                        await StopDashboardAsync();
                        return 0;
                    }
                    case ConsoleKey.S:
                    {
                        await StopDashboardAsync();
                        break;
                    }
                }
            }

            await Task.Delay(5).ConfigureAwait(false);
        }

        async Task RenderLiveInitializationAsync()
        {
            mainLayout["prompt"].Update(new Align(new Text(""), HorizontalAlignment.Left, VerticalAlignment.Bottom));

            AnsiConsole.Clear();
            await AnsiConsole.Live(mainLayout)
                .Overflow(VerticalOverflow.Crop)
                .Cropping(VerticalOverflowCropping.Bottom)
                .StartAsync(async ctx =>
                {
                    var spinner = !AnsiConsole.Console.Profile.Capabilities.Unicode ? Spinner.Known.Ascii : Spinner.Known.Dots;
                    var frameIndex = 0;

                    while (dashboard.IsRunning)
                    {
                        var currentFrame = Markup.FromInterpolated($"[{Widgets.DefaultColorText}]{spinner.Frames[frameIndex % spinner.Frames.Count]}[/]");

                        mainLayout["prompt"].Update(new Align(new Columns(currentFrame, new Text("Waiting for dashboard startup")).Collapse(), HorizontalAlignment.Left, VerticalAlignment.Bottom));
                        UpdateTableCells(currentFrame);
                        ctx.Refresh();

                        if (dashboard.Url != null && dashboard.OtlpEndpoints?.Count == otlpEndpoints.Count)
                        {
                            break;
                        }

                        frameIndex++;
                        await Task.Delay(spinner.Interval);
                    }
                });

            mainLayout["prompt"].Update(new Align(actions, HorizontalAlignment.Left, VerticalAlignment.Bottom));
            UpdateTableCells(defaultStatus);
        }

        async Task StopDashboardAsync()
        {
            await dashboard.StopAsync();

            _dashboardRunning = false;
            table.UpdateCell(0, 0, defaultStatus);
            table.UpdateCell(0, 1, defaultStatus);
            table.UpdateCell(0, 2, defaultStatus);
            mainLayout.Render();
        }

        void UpdateTableCells(Renderable defaultContent)
        {
            table.UpdateCell(0, 0, dashboard.Url is null ? defaultContent : new Columns(Widgets.StatusSymbol(true), Markup.FromInterpolated($"[link]{dashboard.Url}[/]")));
            if (otlpEndpoints.Contains("grpc"))
            {
                var grpcEndpoint = dashboard.OtlpEndpoints?.FirstOrDefault(e => e.Protocol.Contains("grpc", StringComparison.OrdinalIgnoreCase));
                table.UpdateCell(0, 1, grpcEndpoint is null ? defaultContent : new Columns(Widgets.StatusSymbol(true), Markup.FromInterpolated($"[link]{grpcEndpoint.Value.Url}[/]")));
            }

            if (otlpEndpoints.Contains("http"))
            {
                var httpEndpoint = dashboard.OtlpEndpoints?.FirstOrDefault(e => e.Protocol.Contains("http", StringComparison.OrdinalIgnoreCase));
                table.UpdateCell(0, 2, httpEndpoint is null ? defaultContent : new Columns(Widgets.StatusSymbol(true), Markup.FromInterpolated($"[link]{httpEndpoint.Value.Url}[/]")));
            }
        }

        bool CheckDashboardStatusChanged()
        {
            if (dashboard.IsRunning == _dashboardRunning)
            {
                return false;
            }

            _dashboardRunning = false;
            table.UpdateCell(0, 0, defaultStatus);
            table.UpdateCell(0, 1, defaultStatus);
            table.UpdateCell(0, 2, defaultStatus);
            return true;
        }

        bool CheckConsoleSizeChanged()
        {
            if (AnsiConsole.Profile.Width == _currentWidth && AnsiConsole.Profile.Height == _currentHeight)
            {
                return false;
            }

            _currentWidth = AnsiConsole.Profile.Width;
            _currentHeight = AnsiConsole.Profile.Height;
            mainLayout["header"].Update(new Align(new Rows(Widgets.Header(), Widgets.RunnerVersion).Collapse(), HorizontalAlignment.Left, VerticalAlignment.Top));

            return true;
        }

        bool CheckRenderTimeout()
        {
            if (DateTimeOffset.UtcNow - lastRenderTime > TimeSpan.FromSeconds(5))
            {
                lastRenderTime = DateTimeOffset.UtcNow;
                return true;
            }

            return false;
        }
    }

    private static DashboardOptions BuildOptions(Settings args)
    {
        var useHttps = args.OtlpHttps ?? args.UseHttps ?? true;
        var corsConfigured = !string.IsNullOrWhiteSpace(args.CorsAllowedOrigins) || !string.IsNullOrWhiteSpace(args.CorsAllowedHeaders);
        var browserTelemetryEnabled = args.OtlpHttpPort is > 0 and <= 65535 || corsConfigured;

        var aspireDashboardOptions = new DashboardOptions
        {
            Frontend = new FrontendOptions
            {
                BrowserToken = args.AuthToken,
                AuthMode = args.UseAuth || !string.IsNullOrWhiteSpace(args.AuthToken) ? FrontendAuthMode.BrowserToken : FrontendAuthMode.Unsecured,
                EndpointUrls = UrlHelper.BuildLocalUrl(args.DashboardPort, args.DashboardHttps ?? args.UseHttps ?? true, args.Hostname)
            },
            Otlp = new OtlpOptions
            {
                PrimaryApiKey = args.OtlpKey,
                Cors = browserTelemetryEnabled ? new OtlpCorsOptions() : null,
                AuthMode = string.IsNullOrWhiteSpace(args.OtlpKey) ? OtlpAuthMode.Unsecured : OtlpAuthMode.ApiKey
            },
            Runner = new RunnerOptions
            {
                PreferredVersion = args.Version,
                LaunchBrowser = args.LaunchBrowser,
                AutoUpdate = args.AutoUpdate ?? true,
                SingleInstanceHandling = args.AllowMultipleInstances ? SingleInstanceHandling.Ignore : SingleInstanceHandling.ReplaceExisting
            }
        };

        if (args.OtlpPort is > 0 and <= 65535)
        {
            aspireDashboardOptions.Otlp.EndpointUrl = UrlHelper.BuildLocalUrl(args.OtlpPort, useHttps, args.Hostname);
        }

        if (browserTelemetryEnabled)
        {
            aspireDashboardOptions.Otlp.HttpEndpointUrl = UrlHelper.BuildLocalUrl(args.OtlpHttpPort ?? OtlpOptions.DefaultOtlpHttpPort, useHttps, args.Hostname);
        }

        if (aspireDashboardOptions.Otlp.Cors is not null)
        {
            aspireDashboardOptions.Otlp.Cors.AllowedHeaders = args.CorsAllowedHeaders;
            aspireDashboardOptions.Otlp.Cors.AllowedOrigins = args.CorsAllowedOrigins ?? "*";
        }

        return aspireDashboardOptions;
    }

    private static IReadOnlyCollection<string> GetEnabledEndpoints(DashboardOptions dashboardOptions)
    {
        var enabledEndpoints = new List<string>();
        if (dashboardOptions.Otlp.HttpEndpointUrl is not null)
        {
            enabledEndpoints.Add("http");
        }

        if (dashboardOptions.Otlp.EndpointUrl is not null)
        {
            enabledEndpoints.Add("grpc");
        }

        return enabledEndpoints;
    }
}